# Generated by Django 4.2.7 on 2023-11-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.IntegerField(default=1),
        ),
    ]
