# Generated by Django 4.2.7 on 2023-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
