# Generated by Django 4.2.7 on 2023-11-16 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
