# Generated by Django 4.2.7 on 2023-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_activationkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationkey",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
